<ProfileScreen>
    name: 'profile_screen'
    BoxLayout:
        orientation: 'vertical'
        canvas.before:

            Rectangle:
                pos: self.pos
                size: self.size
        canvas:

            Ellipse:
                pos: [self.width/2-72.5, self.height-225]
                size: 150 , 150
                source: 'blank_pic.jpg'
                angle_start: 0
                angle_end: 360

